/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "on-primary-container": "#a8b8ff",
        "on-error-container": "#93000a",
        "surface-border": "#E2E8F0",
        "on-surface": "#191c1e",
        "primary-container": "#1e40af",
        "surface-container-low": "#f2f4f6",
        tertiary: "#25354a",
        "on-secondary": "#ffffff",
        "outline-variant": "#c4c5d5",
        "status-completed": "#3B82F6",
        error: "#ba1a1a",
        "surface-bright": "#f7f9fb",
        "status-rejected": "#EF4444",
        surface: "#f7f9fb",
        primary: "#00288e",
        secondary: "#006a61",
        "surface-container-lowest": "#ffffff",
        "on-background": "#191c1e",
        "on-error": "#ffffff",
        "status-approved": "#10B981",
        "status-pending": "#F59E0B",
        "status-cancelled": "#94A3B8",
        "surface-container": "#eceef0",
        "on-surface-variant": "#444653",
        "surface-container-high": "#e6e8ea",
        background: "#f7f9fb",
        outline: "#757684",
        "error-container": "#ffdad6",
        "surface-dim": "#d8dadc",
        "surface-container-highest": "#e0e3e5",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-md": "16px",
        "stack-sm": "8px",
        gutter: "24px",
        "container-max": "1280px",
        "margin-desktop": "32px",
        "stack-lg": "24px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "headline-sm": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg": ["Inter"],
        "label-sm": ["Inter"],
        "body-lg": ["Inter"],
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
